# jekyll-seo-tag
title: "the New Dynamic"
description: "build faster better websites"
url: https://www.thenewdynamic.org
author: []
twitter:
  username: budparr
facebook:
  app_id:
  publisher:
  admins:
logo: /assets/images/jekyll-white.svg
google_site_verification:
github:
  username: budparr
owner: The New Dynamic
# manifest
short_name: The New Dynamic
display: fullscreen


categories:
  - 'article'
  - 'event'

type:
  - Article
  - Tutorial
  - Presentation


# development meta data
image_url: https://thenewdynamic.imgix.net
google_analytics_id: UA-30899180-4
incremental: false
#port: 3575
utm_parameters_links: '?utm_source=thenewdynamic.org&utm_medium=website&utm_campaign=links'
utm_parameters_showcase: '?utm_source=thenewdynamic.org&utm_medium=website&utm_campaign=showcase'

box_classes: 'bg-white p2'
btn_classes: 'mb4 btn btn-primary bg-primary-color-dark text-decoration-none hover-white hover-bg-black'


wrapper_class: 'p3'

# Settings
production: false
bust_css_cache: false
full_rebuild: true
timezone: Etc/Zulu
compress_html:
  ignore:
    envs: [development]
  profile: false
gems:
  - jekyll-seo-tag
  - jekyll-sitemap
  - octopress-paginate

plugins_dir:  ./_app/_plugins
layouts_dir:  ./_app/_layouts
includes_dir: ./_app/_includes

#permalink: pretty
future: false
# CONTENT
exclude:
  - readme.md
  - todo.md
  - license.md
  - Gemfile
  - Gemfile.lock
  - CNAME
  - node_modules
  - sass
  - gulpfile.js
  - package.json
  - postcss.config.js

# CONTENT
collections:
  landing_pages:
    output: true
    permalink: '/:path/'
  links:
    output: false
    permalink: '/link/:path/'
    future: true
    description: 'Links to from around the web'
  meetups:
      output: false
  showcase:
    output: true
    permalink: '/:collection/:path/'
  tools:
    output: true
    permalink: '/tool/:path/'
  tool_type:
    output: true
    permalink: '/tools/:path/'

# DEFAULTS
defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: page-single
      category: article
  - scope:
      path: ''
      type: events
    values:
      layout: page-single
  - scope:
      path: ''
      type: landing_pages
    values:
      layout: page-single
      feed: false
  - scope:
      path: ''
      type: tool
    values:
      layout: tool
  - scope:
      path: ''
      type: tool_type
    values:
      layout: tools
  - scope:
      path: ''
      type: staff
    values:
      layout: page-single
      feed: false
  - scope:
      path: ''
      type: meetups
    values:
      feed: false
  - scope:
      path: ''
      type: showcase
    values:
      layout: page-listing
  - scope:
      path: '_pages'
    values:
      permalink: /:basename/


staticmanapp:

allowedFields: ['name', 'email', 'comment']
branch: 'gh-pages'
filename: entry{@timestamp}
format: 'json'
generatedFields:
  myField:
    type: date
    options:
      format: timestamp
moderation: true
path: _data/posts/{options.post-slug}
requiredFields: ['name', 'comment']
transforms:
  email: 'md5'  
