# jekyll-seo-tag
title: "the New Dynamic"
description: "Static Site Generators and the Post-CMS paradigm"
url: https://www.thenewdynamic.org
author: []
twitter:
  username: budparr
facebook:
  app_id: 
  publisher: 
  admins: 
logo: /assets/images/jekyll-white.svg
google_site_verification:
github:
  username: budparr
owner: The New Dynamic
# manifest
short_name: The Shortname
display: fullscreen


categories:
  - 'article'
  - 'event'

type:
  - Article
  - Tutorial
  - Presentation


# development meta data
image_url: http://thenewdynamic.imgix.net
google_analytics_id: UA-30899180-4
version: 3.0.3
incremental: true
#port: 3575


# Settings
production: false
bust_css_cache: false
full_rebuild: true
timezone: Etc/Zulu
compress_html:
  ignore:
    envs: [development]
  profile: false
gems:
  - jekyll-seo-tag
  - jekyll-sitemap
plugins_dir:  ./_app/_plugins
layouts_dir:  ./_app/_layouts
includes_dir: ./_app/_includes

permalink: pretty

# CONTENT
exclude:
  - readme.md
  - todo.md
  - license.md
  - Gemfile
  - Gemfile.lock
  - CNAME
  - node_modules
  - sass
  - gulpfile.js
  - package.json
  - postcss.config.js

# CONTENT
collections:
  landing_pages:
    output: true
    permalink: '/:path/'
  links:
    output: false
    permalink: '/link/:path/'
    future: true
    description: 'Links to from around the web'
  meetups:
      output: false
  showcase:
    output: true
    permalink: '/:collection/:path/'
  tool:
    output: true
    permalink: '/:collection/:path/'
  tool_type:
    output: true
    permalink: '/tools/:path/'

# DEFAULTS
defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: page-single
      category: article
  - scope:
      path: ''
      type: events
    values:
      layout: page-single
  - scope:
      path: ''
      type: landing_pages
    values:
      layout: page-single
      feed: false
  - scope:
      path: ''
      type: tool
    values:
      layout: page-listing
  - scope:
      path: ''
      type: tool_type
    values:
      layout: page-listing
  - scope:
      path: ''
      type: staff
    values:
      layout: page-single
      feed: false
  - scope:
      path: ''
      type: meetups
    values:
      feed: false
  - scope:
      path: ''
      type: showcase
    values:
      layout: page-listing
  - scope:
      path: '_pages'
    values:
      permalink: /:basename/